#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# ALIASES
# text editor commands
alias em='emacs -nw'     # No X11 windows
alias eqq='emacs -nw -Q' # No config and no X11

# dev
alias muxkill="tmux kill-session -t"
alias gts="git status"
alias gtd='git diff'
alias gtds='git diff --staged'
alias gtc='git checkout'
alias gtb='git branch'
alias ctf='rm -f **/*~ **/*.orig'

# fix term color for iTerm2 + tmux + emacs
export TERM="xterm"
export NVM_DIR="/Users/tibo/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# added by travis gem
[ -f /Users/tibo/.travis/travis.sh ] && source /Users/tibo/.travis/travis.sh
